name: 执行环境勘探

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: 启动勘探
        run: ./explore.sh
      - name: 上传报告
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.txt
