name: 执行环境勘探

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: 配置 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 配置 Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: 启动勘探
        run: ./explore.sh
        env:
            TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
            TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
            TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
      - name: 上传结果
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: result
